# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test Release

on:
  workflow_dispatch:

env:
  RELEASE_NOTES: ${{ github.repository_owner == 'Xilmi' && 'releaseNotesXilmi.md' || 'releaseNotesBR.md' }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
        cache: 'maven'
    - name: Update apt sources
      run: sudo apt-get update
    - name: Install vorbis-tools / oggenc
      run: sudo apt-get install vorbis-tools
    - name: Install webp / cwebp
      run: sudo apt-get install webp
    - name: Check CPU
      run: sudo cat /proc/cpuinfo
    - name: Build with Maven
      run: mvn -B -fae clean package github-release:github-release -DGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -Dmaven.javadoc.skip=true
           -DrepOwner=${{ github.repository_owner }}
           -DrepName=${{ github.event.repository.name }}
           -DrepFullName=${{ github.repository }}
           -DrepBranch=${{ github.event.repository.ref_name }}
           -Dnotes=$RELEASE_NOTES
           -Dhide=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
